//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acctg_receive_logs
    {
        public int ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public Nullable<int> URGENT { get; set; }
        public Nullable<int> AUDITOR_ID { get; set; }
        public Nullable<int> AUDIT_STATUS_ID { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> TIME_END { get; set; }
        public Nullable<int> AUDIT_RESULT { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string ACCOUNTING_NUMBER { get; set; }
    }
}
