//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class allotment
    {
        public int ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public string ARO_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_ISSUE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
