//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class april
    {
        public int ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public string EXPLANATION { get; set; }
        public string OFFICE { get; set; }
        public string RESPO_CODE { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string RESULT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
    }
}
