//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditor_table
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> USER_TABLE_ID { get; set; }
        public string POSITION { get; set; }
    }
}
