//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_details
    {
        public int ID { get; set; }
        public string BANK { get; set; }
        public string BANK_DESCRIPTION { get; set; }
        public string BRANCH { get; set; }
        public string BANK_MANAGER { get; set; }
        public string BANK_ACCTNO { get; set; }
        public Nullable<int> FUND_ID { get; set; }
    }
}
