//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundle_no
    {
        public int ID { get; set; }
        public Nullable<int> BUNDLE_NO1 { get; set; }
        public Nullable<int> OBR_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
