//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_aa
    {
        public int ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string AA_NO { get; set; }
        public Nullable<int> AA_STATUS { get; set; }
        public string FUND_SOURCE { get; set; }
        public Nullable<int> BANK_ID { get; set; }
        public Nullable<System.DateTime> DATE_PAID { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string DV_NUMBER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<int> CHECK_STATUS { get; set; }
        public string REMARKS { get; set; }
    }
}
