//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_receive
    {
        public int ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string CASH_SERIAL_NO { get; set; }
        public Nullable<int> TRANSMITTAL_STATUS { get; set; }
        public string FUND_SOURCE { get; set; }
        public Nullable<int> BANK_ID { get; set; }
        public Nullable<int> DATE_PAID { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string ACCOUNTING_NUMBER { get; set; }
    }
}
