//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_table
    {
        public int ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string OFFICER { get; set; }
        public string POSITION { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
