//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direct_payment
    {
        public int ID { get; set; }
        public string DOC_NUMBER { get; set; }
        public string EXPLAINATION { get; set; }
        public string PAYEE { get; set; }
        public string ADDRESS { get; set; }
        public string TIN { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> FINAL_AMOUNT { get; set; }
        public string REQUESTING_OFFICIAL { get; set; }
        public string OFFICAIL_POSITION { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public Nullable<int> FUND_TYPE { get; set; }
        public Nullable<int> TRANSACTION_TYPE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<int> TRACER_ID { get; set; }
        public Nullable<int> TRACER_CATEGORY_ID { get; set; }
    }
}
