//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ebayadEntities : DbContext
    {
        public ebayadEntities()
            : base("name=ebayadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aa_records> aa_records { get; set; }
        public DbSet<account_category> account_category { get; set; }
        public DbSet<account_tittle_table> account_tittle_table { get; set; }
        public DbSet<acctg_receive_logs> acctg_receive_logs { get; set; }
        public DbSet<allotment> allotments { get; set; }
        public DbSet<allotment_items> allotment_items { get; set; }
        public DbSet<april> aprils { get; set; }
        public DbSet<audit_result> audit_result { get; set; }
        public DbSet<audit_status> audit_status { get; set; }
        public DbSet<auditor_table> auditor_table { get; set; }
        public DbSet<auditors_note> auditors_note { get; set; }
        public DbSet<bank_details> bank_details { get; set; }
        public DbSet<budget_status> budget_status { get; set; }
        public DbSet<bundle_no> bundle_no { get; set; }
        public DbSet<cafoa> cafoas { get; set; }
        public DbSet<cafoa_items> cafoa_items { get; set; }
        public DbSet<cafoa_status> cafoa_status { get; set; }
        public DbSet<cash_aa> cash_aa { get; set; }
        public DbSet<cash_receive> cash_receive { get; set; }
        public DbSet<cash_transmitallpayroll> cash_transmitallpayroll { get; set; }
        public DbSet<component_table> component_table { get; set; }
        public DbSet<department_table> department_table { get; set; }
        public DbSet<direct_payment> direct_payment { get; set; }
        public DbSet<documents_logs> documents_logs { get; set; }
        public DbSet<fund_source> fund_source { get; set; }
        public DbSet<fund_type> fund_type { get; set; }
        public DbSet<fur> furs { get; set; }
        public DbSet<fur_items> fur_items { get; set; }
        public DbSet<fur_status> fur_status { get; set; }
        public DbSet<liquidation_table> liquidation_table { get; set; }
        public DbSet<lr_cashtransfer_items> lr_cashtransfer_items { get; set; }
        public DbSet<lr_cashtransfer_table> lr_cashtransfer_table { get; set; }
        public DbSet<lr_sdo_items> lr_sdo_items { get; set; }
        public DbSet<lr_sdo_table> lr_sdo_table { get; set; }
        public DbSet<lr_travel_items> lr_travel_items { get; set; }
        public DbSet<lr_travel_table> lr_travel_table { get; set; }
        public DbSet<override_status> override_status { get; set; }
        public DbSet<payroll_deductions> payroll_deductions { get; set; }
        public DbSet<payroll_table> payroll_table { get; set; }
        public DbSet<po_contract_status> po_contract_status { get; set; }
        public DbSet<po_items> po_items { get; set; }
        public DbSet<po_table> po_table { get; set; }
        public DbSet<ppa_object_account> ppa_object_account { get; set; }
        public DbSet<ppa_table> ppa_table { get; set; }
        public DbSet<procurement_air_items> procurement_air_items { get; set; }
        public DbSet<procurement_air_table> procurement_air_table { get; set; }
        public DbSet<procurement_cafoa_status> procurement_cafoa_status { get; set; }
        public DbSet<procurement_delivery_payment_type> procurement_delivery_payment_type { get; set; }
        public DbSet<procurement_voucher_signatory> procurement_voucher_signatory { get; set; }
        public DbSet<rci_table_logs> rci_table_logs { get; set; }
        public DbSet<receiving_status> receiving_status { get; set; }
        public DbSet<release_docs_gso> release_docs_gso { get; set; }
        public DbSet<release_docs_peningyearend_obli> release_docs_peningyearend_obli { get; set; }
        public DbSet<release_status> release_status { get; set; }
        public DbSet<released_docs_table> released_docs_table { get; set; }
        public DbSet<released_docs_table_admin> released_docs_table_admin { get; set; }
        public DbSet<released_docs_table_bac> released_docs_table_bac { get; set; }
        public DbSet<released_docs_table_cash> released_docs_table_cash { get; set; }
        public DbSet<released_docs_table_cbo> released_docs_table_cbo { get; set; }
        public DbSet<released_docs_table_finance> released_docs_table_finance { get; set; }
        public DbSet<released_docs_table_furs> released_docs_table_furs { get; set; }
        public DbSet<released_docs_table_raao_cafoa> released_docs_table_raao_cafoa { get; set; }
        public DbSet<released_docs_table_rrc> released_docs_table_rrc { get; set; }
        public DbSet<released_docs_table_summrypayroll> released_docs_table_summrypayroll { get; set; }
        public DbSet<released_docs_table_toro_cafoa> released_docs_table_toro_cafoa { get; set; }
        public DbSet<released_docs_table_toro_cafoa_claims> released_docs_table_toro_cafoa_claims { get; set; }
        public DbSet<remarks_table> remarks_table { get; set; }
        public DbSet<sample> samples { get; set; }
        public DbSet<sms_container> sms_container { get; set; }
        public DbSet<summary_payroll> summary_payroll { get; set; }
        public DbSet<summary_payroll_items> summary_payroll_items { get; set; }
        public DbSet<supplemental> supplementals { get; set; }
        public DbSet<supplemental_destination_account> supplemental_destination_account { get; set; }
        public DbSet<supplemental_source_account> supplemental_source_account { get; set; }
        public DbSet<supplemental_type> supplemental_type { get; set; }
        public DbSet<toro_category> toro_category { get; set; }
        public DbSet<tracer> tracers { get; set; }
        public DbSet<tracer_category> tracer_category { get; set; }
        public DbSet<tracer_doc_requirements> tracer_doc_requirements { get; set; }
        public DbSet<tracer_doc_requirements_subcat> tracer_doc_requirements_subcat { get; set; }
        public DbSet<tracer_doc_requirements_subcat_ii> tracer_doc_requirements_subcat_ii { get; set; }
        public DbSet<tracking_status> tracking_status { get; set; }
        public DbSet<transaction_table> transaction_table { get; set; }
        public DbSet<transaction_type> transaction_type { get; set; }
        public DbSet<transfer_logs> transfer_logs { get; set; }
        public DbSet<transmittal_records> transmittal_records { get; set; }
        public DbSet<urgentstatu> urgentstatus { get; set; }
        public DbSet<user_status_table> user_status_table { get; set; }
        public DbSet<user_table> user_table { get; set; }
        public DbSet<user_type_table> user_type_table { get; set; }
        public DbSet<voucher_deduction_type> voucher_deduction_type { get; set; }
        public DbSet<voucher_deductions> voucher_deductions { get; set; }
        public DbSet<voucher_table> voucher_table { get; set; }
        public DbSet<yearend_obligations> yearend_obligations { get; set; }
    }
}
