//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_source
    {
        public int ID { get; set; }
        public string FUND_CODE { get; set; }
        public string FUND_NAME { get; set; }
        public Nullable<int> FUND_NO { get; set; }
    }
}
