//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fur
    {
        public int ID { get; set; }
        public string DOC_NUMBER { get; set; }
        public string OBLIGATION_NUMBER { get; set; }
        public string EXPLANATION { get; set; }
        public string PAYEE { get; set; }
        public string ADDRESS { get; set; }
        public string TIN { get; set; }
        public Nullable<double> AMOUNT_REQUESTED { get; set; }
        public Nullable<double> APPROVED_AMOUNT { get; set; }
        public Nullable<double> FINAL_AMOUNT { get; set; }
        public string REQUESTING_OFFICIAL { get; set; }
        public string OFFICAIL_POSITION { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public Nullable<int> TRANSACTION_TYPE_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY { get; set; }
        public string CONTROLLER { get; set; }
        public Nullable<System.DateTime> CONTROLLED_DATE { get; set; }
        public Nullable<int> BANK_NO { get; set; }
        public string SL_CODE { get; set; }
        public Nullable<int> FUR_STATUS { get; set; }
        public Nullable<int> PROCUREMENT { get; set; }
        public string CY { get; set; }
        public Nullable<int> TRACER_ID { get; set; }
        public Nullable<int> TRACER_CATEGORY_ID { get; set; }
    }
}
