//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_cashtransfer_items
    {
        public int ID { get; set; }
        public Nullable<int> LR_CASHTRANSFER_ID { get; set; }
        public string PARTICULARS { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> FINAL_AMOUNT { get; set; }
    }
}
