//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_travel_table
    {
        public int ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public int DEPARTMENT_ID { get; set; }
        public string CLAIMANT { get; set; }
        public string POSISTION { get; set; }
        public Nullable<System.DateTime> LR_DATE { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<int> FUND_SOURCE_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> FINAL_AMOUNT { get; set; }
        public Nullable<double> DV_AMOUNT { get; set; }
        public string DV_NUMBER { get; set; }
        public Nullable<System.DateTime> DV_DATE { get; set; }
        public Nullable<double> REFUND_AMOUNT { get; set; }
        public Nullable<double> FINAL_REFUND_AMOUNT { get; set; }
        public Nullable<double> REIMBURSE_AMOUNT { get; set; }
        public Nullable<double> FINAL_REIMBURSE_AMOUNT { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
