//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_travel_items
    {
        public int ID { get; set; }
        public Nullable<int> LR_TRAVEL_TABLE_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PARTICULARS { get; set; }
        public Nullable<System.TimeSpan> DEPARTURE { get; set; }
        public Nullable<System.TimeSpan> ARRIVAL { get; set; }
        public string TRANSPO_KIND { get; set; }
        public Nullable<double> OTHERS { get; set; }
        public Nullable<double> FINAL_OTHERS { get; set; }
        public Nullable<double> PER_DIEM { get; set; }
        public Nullable<double> FINAL_PER_DIEM { get; set; }
        public Nullable<double> DTE { get; set; }
        public Nullable<double> FINAL_DTE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> FINAL_TOTAL { get; set; }
    }
}
