//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_items
    {
        public int ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public string CAFOA_DOCUMENT_NUMBER { get; set; }
        public Nullable<int> PROCUREMENT_CAFOA_STATUS { get; set; }
    }
}
