//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_table
    {
        public int ID { get; set; }
        public string DOCUMENT_NO { get; set; }
        public string CONTRACT_PO_NUMBER { get; set; }
        public Nullable<System.DateTime> CONTRACT_PO_DATE { get; set; }
        public Nullable<double> CONTRACT_PO_AMOUNT { get; set; }
        public Nullable<int> PO_CONTRACT_STATUS_ID { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string PAYEE { get; set; }
    }
}
