//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppa_object_account
    {
        public int ID { get; set; }
        public Nullable<int> PPA_ID { get; set; }
        public Nullable<int> COMPONENT_ID { get; set; }
        public string RESOURCE { get; set; }
        public Nullable<int> ACCOUNT_TITTLE_ID { get; set; }
        public Nullable<int> BUDGET_STATUS_ID { get; set; }
        public Nullable<int> OUTPUT_NO { get; set; }
        public Nullable<int> FUND_SOURCE_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> ALLOTMENT { get; set; }
    }
}
