//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procurement_air_items
    {
        public int ID { get; set; }
        public Nullable<int> PROCUREMENT_AIR_ID { get; set; }
        public string PO_CONTRACT_NUMBER { get; set; }
        public Nullable<int> PROCUREMENT_DELIVERY_PAYMENT_TYPE_ID { get; set; }
        public string AIR_NUMBER { get; set; }
        public Nullable<System.DateTime> AIR_DATE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<int> AIR_STATUS_PAID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
