//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procurement_voucher_signatory
    {
        public int ID { get; set; }
        public Nullable<int> VOICHER_ID { get; set; }
        public string SIGNATORY { get; set; }
        public string POSITION { get; set; }
        public Nullable<int> DIRECT_PAYMENT_TABLE_ID { get; set; }
        public Nullable<int> PO_TABLE_ID { get; set; }
        public string CONTRACT_PO_NUMBER { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
