//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procurement_air_table
    {
        public int ID { get; set; }
        public int PO_ID { get; set; }
        public string PO_CONTRACT_NUMBER { get; set; }
        public Nullable<double> TOTAL_PO_AMOUNT { get; set; }
        public Nullable<double> CURRENT_AIR_AMOUNT { get; set; }
        public Nullable<double> CURRENT_AIR_BALANCE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    }
}
