//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rci_table_logs
    {
        public int ID { get; set; }
        public Nullable<int> RELEASED_DOC_TABLE_RRC_ID { get; set; }
        public Nullable<System.DateTime> DATE_ENTRY { get; set; }
    }
}
