//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class release_docs_gso
    {
        public int id { get; set; }
        public Nullable<int> po_table_id { get; set; }
        public string document_number { get; set; }
        public Nullable<int> batch_number { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
    }
}
