//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class released_docs_table_cash
    {
        public int ID { get; set; }
        public string DOC_NUMBER { get; set; }
        public Nullable<int> BATCH_NO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public Nullable<int> CASH_AA_ID { get; set; }
    }
}
