//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class summary_payroll
    {
        public int ID { get; set; }
        public string SDO_NAME { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public string EXPLANATION { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> FUND_TYPE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY { get; set; }
        public Nullable<int> TRACER_ID { get; set; }
        public Nullable<int> TRACER_CATEGORY_ID { get; set; }
    }
}
