//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class summary_payroll_items
    {
        public int ID { get; set; }
        public Nullable<int> SUMMARY_PAROLL_ID { get; set; }
        public string PJ_NO { get; set; }
        public string PAYEE { get; set; }
        public string RESPO { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    }
}
