//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracer_doc_requirements_subcat_ii
    {
        public int ID { get; set; }
        public Nullable<int> TRACER_DOC_REQUIREMENTS_SUBCAT_ID { get; set; }
        public string TRACER_DOC_REQUIREMENTS_SUBCAT_II1 { get; set; }
        public string NO_OF_COPIES { get; set; }
    }
}
