//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_deductions
    {
        public int ID { get; set; }
        public Nullable<int> VOUCHER_TABLE_ID { get; set; }
        public string DEDUCTION { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    }
}
